### ISSUE TITLE
Make About page useful

### ISSUE THREAD

**Issue by philsturgeon** [philsturgeon/apibusters.com#1]
A group of folks interested in APIs, who work with them all the time, talking about APIs and postcasting and... 

Somebody make words for that.

**Comment by aligajani** [comment]
Thanks man, looks like some interesting content. Is this entirely new or something from your books?

**Comment by philsturgeon** [comment]
This is going to be a bunch of folks, creating original content but we’re backfilling it with cross-posts so its not empty. 

And a podcast. Which will be fun :)
