### ISSUE TITLE
Use faces for hero images

### ISSUE THREAD

**Issue by phalt** [philsturgeon/apibusters.com#10]
Me: https://apisyouwonthate.slack.com/files/phalt/F0R91TF0A/2015-07-23_15.04.58.jpg

Alex: https://scontent-lhr3-1.xx.fbcdn.net/hphotos-xfp1/t31.0-8/901862_10152688031510523_1270011879_o.jpg

Use these for hero images on blog posts whilst we figure out better ones

**Comment by phalt** [comment]
@philsturgeon do you have one already?

**Comment by philsturgeon** [comment]
I had one of the laptop I bricked in an overnight puddle of hipster orange juice the other day.

I'll try and find another.

**Comment by philsturgeon** [comment]
Doesn't need to be faces! Just a good hero image thats relevant to the content. The newsletter page has this: http://apibusters.com/newsletter/

**Comment by philsturgeon** [comment]
We can do some jekyll magic to use an article_cover: `article_images/whatever-the-fuck.jpg` and override the default author one, but we want to make sure some shit is up there.

**Comment by afolson** [comment]
![image](https://cloud.githubusercontent.com/assets/2797769/14152467/55913156-f668-11e5-95d1-3b59cf684a08.png)

SOON.

**Comment by phalt** [comment]
#14
