### ISSUE TITLE
Replace the damn bridge

### ISSUE THREAD

**Issue by philsturgeon** [philsturgeon/apibusters.com#15]
We got anything for that?

**Comment by phalt** [comment]
Either:
- Something simple like a laptop / coffee on a café table
- Something with our faces (When is Phil and Amanda next in the UK?)
- Just a plain colour?

**Comment by philsturgeon** [comment]
Black actually looks better than nothing. Could do that for a minute.

**Comment by phalt** [comment]
@philsturgeon @alexbilbie we already have https://github.com/philsturgeon/apibusters.com/blob/master/img/feature-laptop.jpg ?

**Comment by philsturgeon** [comment]
I dont wanna use default stock images from the theme we bought from ThemeForest, that seems like a total cop out.
