### ISSUE TITLE
Implement theme

### ISSUE THREAD

**Issue by philsturgeon** [philsturgeon/apibusters.com#2]
- [x] [Option A: Writer](http://jekyllthemes.io/theme/10562560/Writer-A-minimal-blog-for-Jekyll)
- [ ] [Option B: Hipster](https://mmistakes.github.io/hpstr-jekyll-theme/)
- [ ] [Option C: Astro](http://themeforest.net/item/astro-responsive-jekyll-theme/full_screen_preview/8586342?ref=M17)
- [ ] [Option D](http://hyde.getpoole.com/)

**Comment by philsturgeon** [comment]
I vote C, maybe A.

**Comment by alexbilbie** [comment]
A

**Comment by phalt** [comment]
I vote D
Secondary vote: A

**Comment by philsturgeon** [comment]
Ok, going A. Speak now of forever hold your peace. 

Or send me a PR with a better theme whichever. :D

**Comment by philsturgeon** [comment]
Done, basic as. Send PRs!

**Comment by mikestowe** [comment]
I like it :)
